name: Deploy to production

concurrency:
  group: deploy-prod-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout the repo
        uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - id: install-node
        name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - id: install-project-modules
        name: Install project dependencies
        run: npm ci --production
        shell: bash

      - id: validate-metadata
        name: Validate metadata
        if: github.repository != 'thecityny/fullpage-react-template'  # Skip this step when we're on the base template
        run: npm run validate
        shell: bash

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - id: checkout
        name: Checkout the repo
        uses: actions/checkout@v3

      - name: Load .env file
        uses: xom9ikk/dotenv@v2

      - id: install-node
        name: Install Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - id: install-project-modules
        name: Install project dependencies
        run: npm ci --production ## For the app's build routine

      - id: get-slug
        name: Get slug
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            // Pull the slug
            const slug = `${{ env.REACT_APP_SLUG }}`;
            console.log(`slug -> ${slug}`);

            // If we get this far, we're good to go.
            return slug.trim();

      - id: slack
        name: Create Slack notification
        uses: datadesk/notify-slack-on-build@v3
        with:
          slack-token: ${{ secrets.BAKER_BOT_SLACK_TOKEN }}
          channel-id: ${{ secrets.BAKER_BOT_SLACK_CHANNEL_ID }}
          status: in_progress
          url: https://projects.thecity.nyc/${{ steps.get-slug.outputs.result }}/

      - id: npm-build
        name: Build project distribution
        run: npm run build
        env:
          PATH_PREFIX: ${{ steps.get-slug.outputs.result }}

      - id: configure-aws
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_S3_PRODUCTION_REGION }}

      - name: Invalidate CloudFront (clear cache)
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION }}
          PATHS: ${{ format('/{0}/*', steps.get-slug.outputs.result) }}

      - id: npm-deploy
        name: Upload the prepared files
        uses: datadesk/delivery-deploy-action@v1
        with:
          bucket: ${{ secrets.AWS_S3_PRODUCTION_BUCKET }}
          base-path: ${{ steps.get-slug.outputs.result }}
          dir: build
          should-cache: true
          use-accelerate-endpoint: false
          public: true

      - name: Update Slack notification (success)
        if: success()
        uses: datadesk/notify-slack-on-build@v3
        with:
          slack-token: ${{ secrets.BAKER_BOT_SLACK_TOKEN }}
          channel-id: ${{ steps.slack.outputs.channel-id }}
          status: success
          url: https://projects.thecity.nyc/${{ steps.get-slug.outputs.result }}/
          message-id: ${{ steps.slack.outputs.message-id }}

      - name: Update Slack notification (failure)
        if: failure()
        uses: datadesk/notify-slack-on-build@v3
        with:
          slack-token: ${{ secrets.BAKER_BOT_SLACK_TOKEN }}
          channel-id: ${{ steps.slack.outputs.channel-id }}
          status: failure
          url: https://projects.thecity.nyc/${{ steps.get-slug.outputs.result }}/
          message-id: ${{ steps.slack.outputs.message-id }}
